### PR TITLE
Revert the formatting part of the syn wrap change

### LINKED ISSUE #29: Main fn wrapping completely breaks formatting
Screenshot_20240511-093518

this is a regression from #27 (cc @bend-n if you want to fix it, don't have to of course)

i think the wrapping should continue being string based to fully preserve formatting, but using syn to *detect* whether wrapping should be done sounds reasonable.

### PR DESCRIPTION
**Pull request by Nilstrieb**
I did not test this locally. I attempted to revert it as cleanly as possible.
If you prefer I can also revert the *entire* change which has a higher chance of being correct.

fixes #29

### CODE REVIEW

**Comment by Noratrieb** [comment]
I don't have the time to properly set up a local development environment and test a nice fix that does everything nicely. But I very strongly believe that this was a significant regression of functionality and that the previous state was better.

**Comment by bend-n** [comment]
let me test it

**Comment by bend-n** [comment]
it works quite well

**Comment by bend-n** [comment]
hold on you broke unsafe

**Comment by bend-n** [comment]
```patch
diff --git a/src/commands/playground/util.rs b/src/commands/playground/util.rs
index dd1d3d5..3409ca6 100644
--- a/src/commands/playground/util.rs
+++ b/src/commands/playground/util.rs
@@ -247,7 +247,7 @@ pub fn maybe_wrapped(
 	.to_owned();
 
 	if unsf {
-		after_crate_attrs = format!("{unsf}unsafe {{");
+		after_crate_attrs = format!("{after_crate_attrs}unsafe {{");
 	}
 
 	// fn main boilerplate counterpart
diff --git a/src/main.rs b/src/main.rs
index 651ecc1..3140b3e 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -86,8 +86,8 @@ async fn serenity(#[shuttle_runtime::Secrets] secret_store: SecretStore) -> Shut
 					poise::Prefix::Literal("<:ferris:358652670585733120>"),
 					poise::Prefix::Literal("<:ferrisballSweat:678714352450142239> "),
 					poise::Prefix::Literal("<:ferrisballSweat:678714352450142239>"),
-					poise::Prefix::Literal("<:ferrisCat:678714352450142239> "),
-					poise::Prefix::Literal("<:ferrisCat:678714352450142239>"),
+					poise::Prefix::Literal("<:ferrisCat:1183779700485664820> "),
+					poise::Prefix::Literal("<:ferrisCat:1183779700485664820>"),
 					poise::Prefix::Literal("<:ferrisOwO:579331467000283136> "),
 					poise::Prefix::Literal("<:ferrisOwO:579331467000283136>"),
 					poise::Prefix::Regex(
```

**Comment by Noratrieb** [comment]
@ivandardi this is now ready for review, @bend-n tested it so it should work fine

**Review by ivandardi — APPROVED** [review]

**Pull request merged**
